Repository johnbillion/plugin-infrastructure, pull requests merged in 2024-08, with the labels that each got.

#28 Fix some typos in this workflow
  .github/workflows/tidy-up.yml
Labels: pr:wp-crontrol:119, pr:extended-cpts:226, pr:user-switching:125, pr:query-monitor:886

#29 Use a distinct branch for each PR
  .github/workflows/test-plugins.yml
Labels: pr:extended-cpts:227, pr:query-monitor:887, pr:wp-crontrol:120, pr:user-switching:126

#31 Delete the PR branch after closing
  .github/workflows/tidy-up.yml
Labels: pr:query-monitor:888, pr:wp-crontrol:121, pr:extended-cpts:228, pr:user-switching:127

#32 Correct the repo name
  .github/workflows/tidy-up.yml
Labels: pr:extended-cpts:229, pr:query-monitor:889, pr:wp-crontrol:122, pr:user-switching:128

#35 Support testing plugins against forks via a manual workflow dispatcher
  .github/workflows/test-plugins.yml
Labels: pr:user-switching:130, pr:extended-cpts:231, pr:wp-crontrol:124, pr:query-monitor:891

#5 Use MariaDB Docker health check
  bin/acceptance-tests
  bin/integration-tests
  tests/docker-compose.yml
Labels: pr:wp-crontrol:125, pr:query-monitor:892, pr:user-switching:131, pr:extended-cpts:232
